# -*- coding: utf-8 -*-
"""PyTorch_fundamentals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13w5HUnKw6zqiNBG4j8vP8X4_XgvPgrxZ
"""

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

"""#PyTorch Tensors

**Creating Tensor**
"""

# Scalar Tensor

# 0D tensor

# https://docs.pytorch.org/docs/stable/tensors.html

# torch.tensor is a multi-dimensional matrix containing
# elements of a single data type.

scalar=torch.tensor(7)
 scalar

scalar.ndim

# Get tensor back as Python integer

scalar.item()

# Vector

 # 1D tensor

vector=torch.tensor([1,2,3])
vector

vector.ndim

vector.shape

# Matrix

# 2D tensor

matrix=torch.tensor([[1,2],[3,4]])
matrix

matrix.ndim

matrix.shape

matrix[0]

matrix[1]

# Tensor

ten=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
ten

ten.ndim

ten.shape

ten[0]

"""# Creating Random Tensor"""

# Why random tensor

# Random tensors are important because the way
# many neural netowkrs learn is that they start with
# tensors full of random numbers and then adjust
# those random numbers to better represent the data.

# Start with random number -> look at data-> update
# random numbers -> look at data -> update random numbers

# create a random tensor of size (3,4)
# Uniform random tensor
# torch.rand()

# Values are sampled from a uniform distribution between
# 0(inclusive) and 1 (exclusive)

# [0,1)

# shape:- 3 rows , 4 columns

random_tensor=torch.rand(3,4)
random_tensor

random_tensor.ndim

random_tensor.shape

random_tensor[0]

random_tensor[1]

random_tensor[2]

# create a random tensor with similar
# shape to an  image tensor

# 3 channels(R,G,B), height,width
image_tensor=torch.rand(size=(3,224,224))
image_tensor.shape,image_tensor.ndim

# Normal(Gaussian) Distribution

# torch.randn()

# Values are drawn from a standard normal distribution
# mean=0 & std=1

# Useful for intializing weights in Neural Network.

ten_normal=torch.randn(3,4)
ten_normal

ten_normal.ndim

ten_normal.shape

ten_normal[0]

ten_normal[1]

ten_normal[2]

# Random Integers

# torch.randint()

# Returns a tensor of random integers in the range
# ([low,high]) with shape(2,4)

random_tensor=torch.randint(0,10,(2,4))
random_tensor

random_tensor.ndim

random_tensor.shape

random_tensor[0]

random_tensor[1]

# Random Binary Tensor(Bernoulli Distribution)

# torch.bernoulli()

# Return a 0 or 1 based on the given probabilities

probs = torch.tensor([[0.1, 0.8], [0.7, 0.3]])
tensor = torch.bernoulli(probs)
print(tensor)

# Set  Random seed for Reproducibility

torch.manual_seed(32)

random_tensor=torch.randint(0,10,(2,3))
random_tensor

"""# Creating Tensors with Zeros and Ones

"""

#rows,columns

zero_tensor=torch.zeros(2,3)
zero_tensor

zero_tensor.dtype

one_tensor=torch.ones(2,3,dtype=torch.int32)
one_tensor

one_tensor.dtype

# set up a data type

one_data_type=torch.ones(size=(3,4),dtype=torch.int32)
one_data_type

"""# Creating a Tensor Range and Tensors like other Tensors"""

# Use torch.arange()

# will include 1st value and exclude last value

one_to_ten=torch.arange(1,11)
one_to_ten

# Values from 0 to 100 with step 5

# it will include 0 and exclude 100

tensors = torch.arange(start=0,end=100,step=5)
tensors

# creating a tensors "Like" another tensor

x = torch.tensor([[1,2,3],[4,5,6]])
x

# torch.zeros_like(x)

zero_like=torch.zeros_like(x)
zero_like

zero_like.dtype

# torch.ones_like(x)

one_like=torch.ones_like(x)
one_like

one_like.dtype

# torch.rand_like

torch.manual_seed(32)

random_like=torch.rand_like(x,dtype=torch.float)
random_like

"""# Dealing with Tensor Data Types"""

# float 32 tensor

float_32= torch.tensor([1.0,2.0,3.0],dtype=None)
float_32

float_32.dtype

# default data type in PyTorch in float 32

# dtype:- What Data Type is tensor(e.g: float32,int64)

# device:- What devide is your tensor on

# require_grad:- Whether or not to track gradients with
# tensor operations

# most important parameters while creating tensors

"""
Note:- Tensor DataType is one of the 3 big errors you'll
run into with PyTorch and Deep Learning

1.) Tensors not right datatype

2.) Tensors not right shape

3.) Tensors not the right device

"""

float_32= torch.tensor([1.0,2.0,3.0],dtype=None,
                       device="cpu",
                       requires_grad=True)
float_32

float_16= float_32.type(torch.float16)
float_16

float_16.dtype

x = torch.tensor([1, 2, 3])
print(x.device)  # cpu

# Move to GPU
if torch.cuda.is_available():
    x = x.to("cuda")
    print(x.device)  # cuda:0

float_32

float_16

float_16*float_32

(float_16*float_32).dtype

int_32=torch.tensor([2,3,4],dtype=torch.int32)
int_32

int_32*float_32

(int_32*float_32).dtype

# Getting information from tensors

# 1.) Tensors not right datatype
# To do get datatype from a tensor, can use tensor.dtype

# 2.) Tensors not right shape
# to get shape from a tensor, can use tensor.shape

# 3.) Tensors not on the right device
# to get device from a tensor, can use tensor.device

# create a tensor

new_tensor=torch.rand(3,4)
new_tensor

new_tensor.dtype

new_tensor.shape

new_tensor.size() # size is a function and shape
# is attribute

# () at the end meaning its a method

new_tensor.device

# What is precision in computing?

# In computer science, the precision of a numerical
# quantity is a measure of the detail in which
# the quantity is expressed. This is usually
# measured in bits, but sometimes in decimal
# digits. It is related to precision in
# mathematics, which describes the number of
# digits that are used to express a value.

"""# Tensor Operations"""

# Tensor Operations


# 1.) Addition

# 2.) Subtraction

# 3.) Multiplication (Element wise)

# 4.) Division

# 5.) Matrix Multiplication

# create a tensor


tensor= torch.tensor([1,2,3])

new_tensor=tensor + 10
new_tensor

torch.add(tensor,10)

mul_tensor= tensor*10
mul_tensor

torch.mul(tensor,10)

sub_tensor = tensor-1
sub_tensor

torch.sub(tensor,1)

tensor

d_tensor=torch.tensor([10,20,30])

div_tensor=d_tensor/10
div_tensor

torch.div(d_tensor,10)

"""# Matrix Multiplication"""

# Two main ways of perfoming multiplication in
# Neural Network and Deep Learning

# 1.) Element vise Multiplication

# 2.) Matrix Multiplication - Dot Product

# There are two main rules that perfoming matrix
# Multiplication needs to satisfy:

# 1.) The **inner dimension must match

# (3,2) * (3,2) will not work
# (2,3) * (3,2) will work
# (3,2) * (2,3) will work

# 2.) The resulting matrix has the shape of the
# ** Outer dimension

# (2,3) * (3,2) = (2,2)
# (3,2) * (2,3) = (3,3)

# 1.) Element vise Mulitplication

tensor= torch.tensor([1,2,3])
tensor

tensor*tensor

# Matrix Multiplication

torch.matmul(tensor,tensor)

# [1,2,3] * [1,2,3] = [1*1 + 2*2 + 3*3]=1+4+9=14

# One of the most common errors in deep learning
# is Shape errors

tensor_A =torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_A

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
tensor_B

tensor_A.shape,tensor_B.shape

"""
torch.matmul(tensor_A,tensor_B)

RuntimeError         Traceback (most recent call last)
/tmp/ipython-input-1993702425.py in <cell line: 0>()
----> 1 torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be
multiplied (3x2 and 3x2)
"""

# To fix tensor shape issue, we can manipulate shape
# of one of our tensors using matrix transpose

# A Transpose switches the axes or dimensions of a
# given tensor.

tensor_B

tensor_B.T

tensor_B.shape,tensor_B.T.shape

torch.matmul(tensor_A,tensor_B.T)

torch.matmul(tensor_A,tensor_B.T).shape

# Matrix Multiplication using "@"

t_A=torch.tensor([[1,2],
                [3,4]])
print(t_A)

print("\n")

print(t_A.shape)

t_B=torch.tensor([[1,2,3],
                [4,5,6]])
print(t_B)

print("\n")

print(t_B.shape)

C = t_A @ t_B
C

# torch.mm()

# Only for 2D tensors

torch.mm(t_A,t_B)

# torch.bmm() - Batch Matrix Multiplication
# 3D tensors only

A = torch.randn(1, 3, 4)
B = torch.randn(1, 4, 5)

print(A)

print("\n")

print(B)

print("\n")

C = torch.bmm(A, B)         # Result: (1, 3, 5)
print(C)

"""# Finding the Min, Max, and Sum of Tensors (Tensor Aggregation)"""

# creat a tensor

x= torch.tensor([[1,2],[3,4]])
x

# Find the min

torch.min(x), x.min()

torch.min(x,dim=0) # Colum wise minimum value

torch.min(x,dim=1) # Row wise minimum value

# Find the max

torch.max(x),x.max()

torch.max(x,dim=0) # Colum wise maximum value

torch.max(x,dim=1) # Row wise maximum value

# Find the mean

# torch.mean(x),x.mean()

# RuntimeError: mean(): could not infer output dtype.
# Input dtype must be either
# a floating point or complex dtype. Got: Long

# to find mean tensor's data type must be float

torch.mean(x.float()), x.float().mean()

# other way to convert into float data type

torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

torch.mean(x.float(),dim=0) # Column wise mean

torch.mean(x.float(),dim=1) # Row wise mean

# Find the sum

torch.sum(x),x.sum()

torch.sum(x,dim=0) # Column wise sum

torch.sum(x,dim=1) # Row wise sum

"""# Find the Positional Max and Min of Tensors"""

x= torch.tensor([[1,2],[3,4]])
x

# Find the position in tensor that has the minimum
# value with argmin()- returns the index position
# of target tensor where minimum value occurs

x.argmin(),torch.argmin(x)

# Find the position in tensor that has the maximum
# value with argmax()

torch.argmax(x),x.argmax()

"""# Other Tensor Aggregation function"""

# Product of all elements

x=torch.tensor([[1,2],[3,4]])

torch.prod(x) # 1*2*3*4=24

# standard deviation

x = torch.tensor([1,2,3,4])

torch.std(x.float())

# variance

x = torch.tensor([1,2,3,4])

torch.var(x.float())

# Cumulative sum
# dim=0 is must parameter
x = torch.tensor([1,2,3,4,5,6,7,8,9,10])

torch.cumsum(x,dim=0)

# Cumulative product

# dim=0 is must parameter

x = torch.tensor([1,2,3,4,5])

torch.cumprod(x,dim=0)

# Meadian and Mode

x = torch.tensor([1,2,3,3,4])

print("Median Value of x: -",torch.median(x))

print("\n")

print("Mode of x :- ",torch.mode(x))

# keepdim parameter

# Whether to retain reduced dimension as size 1
# for example:- [2,1] instead of [2,]

x = torch.tensor([[1,2],[3,4]])
print(x)

print("\n")

total_column_wise=torch.sum(x,dim=0,keepdim=True)

print("total_column_wise :- ",total_column_wise)

print("\n")

total_row_wise=torch.sum(x,dim=1,keepdim=True)

print("total_row_wise :-",total_row_wise)

"""# Reshaping, Viewing and Stacking Tensors"""

# Reshaping :- Reshapes an input tensor to a defined
# shape

# View :- Return a view of an input tensor of certain
# shape but keep the same memory as the original tensor

# Stacking :- Combine multiple tensor on top of each
# other.

# Create a tensor

import torch

x = torch.arange(1.,10.)
print(x)
print("\n")
print(x.shape)

# Add an extra dimension
# when we change the shape of the tensor
# the new shape must be compatible with the existing
# tensor


# reshape_x=x.reshape(1,7)
# reshape_x,reshape_x.shape

# Add an extra dimension
"""
----> 3 reshape_x=x.reshape(1,7)
      4 reshape_x,reshape_x.shape

RuntimeError: shape '[1, 7]' is invalid
for input of size 9"""

# 1 extra dimension will be added outside

reshape_x=x.reshape(1,9)
reshape_x,reshape_x.shape

reshape_x=x.reshape(3,3)
reshape_x,reshape_x.shape

# 1 extra dimentions will be added inside
reshape_x=x.reshape(9,1)
reshape_x,reshape_x.shape

# it will work with (1,9)/(9,1)

# other combinations will give an error

# as long as the given dimension can reshape it
# evenly it will work

# Change the view

z = x.view(1,9)
z,z.shape

# changing z changes x because view of a tensor
# share the same memory as the original tensor

z[:,0]=5
z,x

# Stack tensors on top of each other


x = torch.arange(1.,5.)

x_stack = torch.stack([x,x,x,x],dim=0)
x_stack

y_stack = torch.stack([x,x,x,x],dim=1)
y_stack

"""# Other Functions"""

# flatten() - Collaps dimenstions into 1
# combine values in one 1 dimension

x = torch.tensor([[1,2],[3,4]])
print(x.flatten())

print(x.view(x.size(0),-1))

#flatten everything except batch

"""# Squeezing, Unsquezeeing and Permuting Tensors"""

# Squeeze :- Removes all 'single' dimenstions from a
# tensor

# Unsqueeze :- Add a '1' dimension to a target tensor

# Permute :-  Reorder dimensions
# Changes the order of axes(dimenstions) of a tensor

x = torch.arange(1.,10.)
print(x)

print("\n")

x=x.reshape(1,9)
print("New tensor:- ",x)

print("\n")

print(x.reshape(1,9).shape)

# will remove 1 dimension
# in simple term it will remove one square bracket

x_squeeze=x.squeeze()
x_squeeze

x_squeeze.shape

x

x = torch.arange(1.,10.)
print(x)

x_unsqueeze= x.unsqueeze(0)
x_unsqueeze

x_unsqueeze.shape

x_unsqueeze= x.unsqueeze(1)
x_unsqueeze

x_unsqueeze.shape

# permuting a tensor

torch.manual_seed(32)

x = torch.rand(size=(2,2,3))
# height,width,colour_channels
x

x.shape

# Permute the original tensor to rearragne the axis
 # or dim order

x_permute=x.permute(2,0,1)
x_permute.shape

x_permute

"""# Selecting Data From Tensors(Indexing)"""

# Select data from tensor using index

# Indexing the PyTorch is similar to indexing with
# NumPy

# create a tensor

x = torch.arange(1,10)
x,x.shape

x = x.reshape(1,3,3)
x

x[0]

x[0][0] # dim=1

x[0][0][0] # last dimension

# x[1][1][1]

# IndexError: index 1 is out of bounds for
# dimension 0 with size 1

x[0][1][1]

x[0][2][2]

# use ":" to select all targe dimensions

x[:,0]

# all values of 0th and 1st dimension but only
# index 1 of 2nd dimension

x[:,:,1]

# get all values of the 0 dimension but only
# 1 index value of 1st and 2nd dimension


x[:,1,1]

x[0,1,1]

# get index 0 of 0th dimension. and 1st dimension and
# all value of 2nd dimension

x[0,0,:]

x

x[0,2,2]

x[0,2,:]

"""# PyTorch Tensors and NumPy"""

#  Numpy is a popular scientific Python Numerical
# computing library

# And because of this , PyTorch has functionality
# to interact with it.

# Data in NumPy , want in PyTorch tensor
# torch.from_numpy(ndarray)

# from PyTorch to NumPy
# torch.Tensor.numpy()

import torch
import numpy as np

arr = np.arange(1.0,8.0)
arr, arr.dtype

tensor=torch.from_numpy(arr)
tensor

# change the value of an array, let's see how it
# affects our tensor

arr= arr+1
arr,tensor

# it will not change the value of a tensor

# tensor to numpy

tensor=torch.ones(7)
tensor

tensor.dtype

numpy_tensor=tensor.numpy()
numpy_tensor

# change the tensor, let's see what happens
# to numpy array

tensor=tensor+1
tensor,numpy_tensor

"""# PyTorch Reproducability (Taking the Random out of Random)"""

# Ensuring Reproducability in PyTorch means making sure
# our results stay the same every time we run the code,
# even if it uses randomness
# e.g:- weight initialization, shuffling data, dropout

# In short how Neural Network learns :-

# start with random numbers -> tensor opersations->
# update random numbers to try and make them better
# representations of the data -> repeat the process

# To reduce the randomness in neural network and
# PyTorch comes the concept of a "random seed"

# create a tensor

import torch

random_tensor_A =  torch.rand(3,4)
random_tensor_B =  torch.rand(3,4)

print(random_tensor_A)
print("\n")
print(random_tensor_B)
print("\n")
print(random_tensor_A==random_tensor_B)

# let's create random but reproducible tensors

import torch
import random
import numpy as np

# set the random seed
seed=18

torch.manual_seed(seed)

random.seed(seed)
np.random.seed(seed)

random_tensor_C =  torch.rand(3,4)
random_tensor_D =  torch.rand(3,4)

print(random_tensor_C)
print("\n")
print(random_tensor_D)
print("\n")
print(random_tensor_C==random_tensor_D)

# setup seed each time before creating a tensor

torch.manual_seed(seed)
random_tensor_C =  torch.rand(3,4)

torch.manual_seed(seed)
random_tensor_D =  torch.rand(3,4)

print(random_tensor_C)
print("\n")
print(random_tensor_D)
print("\n")
print(random_tensor_C==random_tensor_D)

"""# Different Ways of Accessing a GPU in PyTorch"""

# Running tensors and PyTorch objects on the GPUs
# makes faster computations

# Getting GPU

# Use Google Colab for free GPU
# Buy your own GPU
# Use cloud AWS,Azure,GCP

"""
import torch

print(torch.cuda.is_available()) # True if GPU is available

print("\n")

print(torch.cuda.device_count()) # Number of GPUs

print("\n")

print(torch.cuda.get_device_name(0)) # Name of the first GPU
"""

!nvidia-smi

# Setup device agnostic code


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

"""# Setting up Device - Agnostic code and Putting Tensors On and Off the GPU




"""

# The reason we want our tensors/models on the GPU is
# because
# using a GPU results in faster computations

# Create a tensor (default on the CPU)

tensor=torch.tensor([1,2,3,4])

tensor,tensor.device

# Move tensor to GPU

tensor_gpu=tensor.to(device)

tensor_gpu

# Moving tensor back to CPU

# If tensor is on GPU ,can't transfer it to NumPy

# tensor_gpu.numpy()

#TypeError: can't convert cuda:0 device type tensor
#to numpy. Use Tensor.cpu() to copy the tensor to host
#memory first.

# To fix the GPU tensor with Numpy issue,
# we can first set it to the CPU

tensor_gpu_to_cpu=tensor_gpu.cpu().numpy()
tensor_gpu_to_cpu